sudo: required
services:
  - docker

before_install:
  - docker build -t vivdan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vivdan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-481357223283"
  bucket_path: "docker_react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
